# Build settings
markdown: rdiscount
highligher: pygments

# Site settings
title: "Paul Osman"
description: >
  Ramblings about technology, management, cycling, travel, etc

email: paul@eval.ca
logo: "/assets/images/logo.jpg"
cover: "/assets/images/background.jpg"

disqus_shortname: paulosman

name: "Paul Osman"
author: "Paul Osman"
author_image: "/assets/images/profile.jpg"

paginate: 5

url: "http://paulosman.me"
baseurl: ""

social:
  - icon: twitter
    url: https://twitter.com/paulosman
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/paulosman
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

