# Build settings
markdown: kramdown
highligher: pygments

# Site settings
title: "Paul Osman"
description: >
  Thoughts on technology, management, cycling, running, travel and more.

email: paul@eval.ca
logo: "/assets/images/logo.jpg"
cover: "/assets/images/background.jpg"

disqus_shortname: paulosman

name: "Paul Osman"
author: "Paul Osman"
author_image: "/assets/images/profile.jpg"

paginate: 5
gems: [jekyll-paginate]

url: "http://paulosman.me"
baseurl: ""

social:
  - icon: twitter
    url: https://twitter.com/paulosman
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: instagram
    url: https://instagram.com/paulosman
    desc: Follow me on instagram
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/paulosman
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: stack-overflow
    url: http://stackoverflow.com/users/195977/paul-osman
    desc: StackOverflow
    share_url:
    share_title:
    share_link:

  - icon: facebook
    url: https://www.facebook.com/paulosman
    desc: Follow me on facebook
    share_url: https://www.facebook.com/sharer/sharer.php
    share_title: ?u=
    share_link:

  - icon: linkedin
    url: https://www.linkedin.com/in/paulosman
    desc: Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:
